# Generated by Django 3.2.6 on 2021-08-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carol', '0002_skills_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
